"""
EMA + Alarm score simulation — SCENARIO injected from device.

Fetched : 2026-04-15T16:04:59
Source  : http://192.168.10.2
Records : 60

Run:
    python tests/sim_20260415_160459.py
"""

import sys
from pathlib import Path

# Locate docs/ relative to this file so sim1 is importable regardless of cwd
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "docs"))
import sim1

# ═══════════════════════════════════════════════════════════════════
#  CONFIGURATION — copied from device at fetch time
# ═══════════════════════════════════════════════════════════════════

INITIAL_EMA  = 149.8357   # back-calculated EMA before oldest record
ALPHA        = 0.2
CLAMP        = 0.4

ZONE_GREEN   = 40
ZONE_YELLOW  = 200

P1 = 0.1
P2 = 0.8

# ═══════════════════════════════════════════════════════════════════
#  SCENARIO — fetched from device (oldest → newest)
# ═══════════════════════════════════════════════════════════════════

SCENARIO = [
    107.17, 223.33, 96.93, 89.09, 139.26, 139.10, 167.99, 212.89, 218.05, 155.78,
    301.00, 135.70, 6.88, 544.63, 957.45, 1008.40, 1212.12, 14.76, 1281.14, 1572.05,
    1220.34, 717.13, 1176.47, 1978.02, 1228.67, 1343.28, 617.50, 214.03, 148.64, 222.36,
    223.60, 209.55, 166.13, 135.24, 166.51, 199.12, 143.54, 137.56, 122.57, 100.98,
    195.44, 66.83, 255.86, 146.88, 185.28, 175.35, 168.07, 178.39, 166.44, 5070.42,
    873.79, 147.54, 71.80, 82.83, 72.58, 137.88, 140.52, 7.96, 30000.00, 30000.00,3000.00,300.00,300.00,293.02,
]

FLOW_RATES = SCENARIO

# ═══════════════════════════════════════════════════════════════════
#  DATA INSPECTION — raw device snapshot
# ═══════════════════════════════════════════════════════════════════

_RAW = {   'alg': {   'alarm_p1': 0.2,
               'alarm_p2': 0.8,
               'ema_alpha': 0.2,
               'ema_clamp': 0.4,
               'initial_ema': 200,
               'success': True,
               'zone_green': 40,
               'zone_yellow': 200},
    'cycles': [   {   'alert': 2,
                      'cycle': 145,
                      'dev_sigma': 0,
                      'hour': 10,
                      'interval_s': 172,
                      'rate_ml_h': 2093.023,
                      'red_alert': True,
                      'ts': 1776240768},
                  {   'alert': 1,
                      'cycle': 144,
                      'dev_sigma': 0,
                      'hour': 10,
                      'interval_s': 12,
                      'rate_ml_h': 30000,
                      'red_alert': False,
                      'ts': 1776240596},
                  {   'alert': 0,
                      'cycle': 143,
                      'dev_sigma': 0,
                      'hour': 10,
                      'interval_s': 45238,
                      'rate_ml_h': 7.957911,
                      'red_alert': False,
                      'ts': 1776240584},
                  {   'alert': 0,
                      'cycle': 142,
                      'dev_sigma': 0,
                      'hour': 21,
                      'interval_s': 2562,
                      'rate_ml_h': 140.5152,
                      'red_alert': False,
                      'ts': 1776195346},
                  {   'alert': 0,
                      'cycle': 141,
                      'dev_sigma': 0,
                      'hour': 20,
                      'interval_s': 2611,
                      'rate_ml_h': 137.8782,
                      'red_alert': False,
                      'ts': 1776192784},
                  {   'alert': 0,
                      'cycle': 140,
                      'dev_sigma': 0,
                      'hour': 20,
                      'interval_s': 4960,
                      'rate_ml_h': 72.58064,
                      'red_alert': False,
                      'ts': 1776190173},
                  {   'alert': 0,
                      'cycle': 139,
                      'dev_sigma': 0,
                      'hour': 18,
                      'interval_s': 4346,
                      'rate_ml_h': 82.83479,
                      'red_alert': False,
                      'ts': 1776185213},
                  {   'alert': 0,
                      'cycle': 138,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 5014,
                      'rate_ml_h': 71.79896,
                      'red_alert': False,
                      'ts': 1776180867},
                  {   'alert': 0,
                      'cycle': 137,
                      'dev_sigma': 0,
                      'hour': 16,
                      'interval_s': 2440,
                      'rate_ml_h': 147.541,
                      'red_alert': False,
                      'ts': 1776175853},
                  {   'alert': 1,
                      'cycle': 136,
                      'dev_sigma': 0,
                      'hour': 15,
                      'interval_s': 412,
                      'rate_ml_h': 873.7864,
                      'red_alert': False,
                      'ts': 1776173413},
                  {   'alert': 1,
                      'cycle': 135,
                      'dev_sigma': 0,
                      'hour': 15,
                      'interval_s': 71,
                      'rate_ml_h': 5070.422,
                      'red_alert': False,
                      'ts': 1776173001},
                  {   'alert': 0,
                      'cycle': 134,
                      'dev_sigma': 0,
                      'hour': 15,
                      'interval_s': 2163,
                      'rate_ml_h': 166.4355,
                      'red_alert': False,
                      'ts': 1776172930},
                  {   'alert': 0,
                      'cycle': 133,
                      'dev_sigma': 0,
                      'hour': 14,
                      'interval_s': 2018,
                      'rate_ml_h': 178.3944,
                      'red_alert': False,
                      'ts': 1776170767},
                  {   'alert': 0,
                      'cycle': 132,
                      'dev_sigma': 0,
                      'hour': 14,
                      'interval_s': 2142,
                      'rate_ml_h': 168.0672,
                      'red_alert': False,
                      'ts': 1776168749},
                  {   'alert': 0,
                      'cycle': 131,
                      'dev_sigma': 0,
                      'hour': 13,
                      'interval_s': 2053,
                      'rate_ml_h': 175.3531,
                      'red_alert': False,
                      'ts': 1776166607},
                  {   'alert': 0,
                      'cycle': 130,
                      'dev_sigma': 0,
                      'hour': 13,
                      'interval_s': 1943,
                      'rate_ml_h': 185.2805,
                      'red_alert': False,
                      'ts': 1776164554},
                  {   'alert': 0,
                      'cycle': 129,
                      'dev_sigma': 0,
                      'hour': 12,
                      'interval_s': 2451,
                      'rate_ml_h': 146.8788,
                      'red_alert': False,
                      'ts': 1776162611},
                  {   'alert': 0,
                      'cycle': 128,
                      'dev_sigma': 0,
                      'hour': 11,
                      'interval_s': 1407,
                      'rate_ml_h': 255.8635,
                      'red_alert': False,
                      'ts': 1776160160},
                  {   'alert': 0,
                      'cycle': 127,
                      'dev_sigma': 0,
                      'hour': 11,
                      'interval_s': 5387,
                      'rate_ml_h': 66.82755,
                      'red_alert': False,
                      'ts': 1776158753},
                  {   'alert': 0,
                      'cycle': 126,
                      'dev_sigma': 0,
                      'hour': 9,
                      'interval_s': 1842,
                      'rate_ml_h': 195.4397,
                      'red_alert': False,
                      'ts': 1776153366},
                  {   'alert': 0,
                      'cycle': 125,
                      'dev_sigma': 0,
                      'hour': 9,
                      'interval_s': 3565,
                      'rate_ml_h': 100.9818,
                      'red_alert': False,
                      'ts': 1776151524},
                  {   'alert': 0,
                      'cycle': 124,
                      'dev_sigma': 0,
                      'hour': 8,
                      'interval_s': 2937,
                      'rate_ml_h': 122.5741,
                      'red_alert': False,
                      'ts': 1776147959},
                  {   'alert': 0,
                      'cycle': 123,
                      'dev_sigma': 0,
                      'hour': 7,
                      'interval_s': 2617,
                      'rate_ml_h': 137.5621,
                      'red_alert': False,
                      'ts': 1776145022},
                  {   'alert': 0,
                      'cycle': 122,
                      'dev_sigma': 0,
                      'hour': 6,
                      'interval_s': 2508,
                      'rate_ml_h': 143.5407,
                      'red_alert': False,
                      'ts': 1776142405},
                  {   'alert': 0,
                      'cycle': 121,
                      'dev_sigma': 0,
                      'hour': 6,
                      'interval_s': 1808,
                      'rate_ml_h': 199.1151,
                      'red_alert': False,
                      'ts': 1776139897},
                  {   'alert': 0,
                      'cycle': 120,
                      'dev_sigma': 0,
                      'hour': 5,
                      'interval_s': 2162,
                      'rate_ml_h': 166.5125,
                      'red_alert': False,
                      'ts': 1776138089},
                  {   'alert': 0,
                      'cycle': 119,
                      'dev_sigma': 0,
                      'hour': 5,
                      'interval_s': 2662,
                      'rate_ml_h': 135.2367,
                      'red_alert': False,
                      'ts': 1776135927},
                  {   'alert': 0,
                      'cycle': 118,
                      'dev_sigma': 0,
                      'hour': 4,
                      'interval_s': 2167,
                      'rate_ml_h': 166.1283,
                      'red_alert': False,
                      'ts': 1776133265},
                  {   'alert': 0,
                      'cycle': 117,
                      'dev_sigma': 0,
                      'hour': 3,
                      'interval_s': 1718,
                      'rate_ml_h': 209.546,
                      'red_alert': False,
                      'ts': 1776131098},
                  {   'alert': 0,
                      'cycle': 116,
                      'dev_sigma': 0,
                      'hour': 3,
                      'interval_s': 1610,
                      'rate_ml_h': 223.6025,
                      'red_alert': False,
                      'ts': 1776129380},
                  {   'alert': 0,
                      'cycle': 115,
                      'dev_sigma': 0,
                      'hour': 2,
                      'interval_s': 1619,
                      'rate_ml_h': 222.3595,
                      'red_alert': False,
                      'ts': 1776127770},
                  {   'alert': 0,
                      'cycle': 114,
                      'dev_sigma': 0,
                      'hour': 2,
                      'interval_s': 2422,
                      'rate_ml_h': 148.6375,
                      'red_alert': False,
                      'ts': 1776126151},
                  {   'alert': 0,
                      'cycle': 113,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 1682,
                      'rate_ml_h': 214.0309,
                      'red_alert': False,
                      'ts': 1776123729},
                  {   'alert': 1,
                      'cycle': 112,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 583,
                      'rate_ml_h': 617.4957,
                      'red_alert': False,
                      'ts': 1776122047},
                  {   'alert': 1,
                      'cycle': 111,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 268,
                      'rate_ml_h': 1343.284,
                      'red_alert': False,
                      'ts': 1776121464},
                  {   'alert': 1,
                      'cycle': 110,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 293,
                      'rate_ml_h': 1228.669,
                      'red_alert': False,
                      'ts': 1776121196},
                  {   'alert': 1,
                      'cycle': 109,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 182,
                      'rate_ml_h': 1978.022,
                      'red_alert': False,
                      'ts': 1776120903},
                  {   'alert': 1,
                      'cycle': 108,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 306,
                      'rate_ml_h': 1176.471,
                      'red_alert': False,
                      'ts': 1776120721},
                  {   'alert': 1,
                      'cycle': 107,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 502,
                      'rate_ml_h': 717.1315,
                      'red_alert': False,
                      'ts': 1776120415},
                  {   'alert': 1,
                      'cycle': 106,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 295,
                      'rate_ml_h': 1220.339,
                      'red_alert': False,
                      'ts': 1776119913},
                  {   'alert': 1,
                      'cycle': 105,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 229,
                      'rate_ml_h': 1572.052,
                      'red_alert': False,
                      'ts': 1776119618},
                  {   'alert': 1,
                      'cycle': 104,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 281,
                      'rate_ml_h': 1281.139,
                      'red_alert': False,
                      'ts': 1776119389},
                  {   'alert': 0,
                      'cycle': 103,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 24398,
                      'rate_ml_h': 14.75531,
                      'red_alert': False,
                      'ts': 1776119108},
                  {   'alert': 1,
                      'cycle': 102,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 297,
                      'rate_ml_h': 1212.121,
                      'red_alert': False,
                      'ts': 1776094710},
                  {   'alert': 1,
                      'cycle': 101,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 357,
                      'rate_ml_h': 1008.403,
                      'red_alert': False,
                      'ts': 1776094413},
                  {   'alert': 1,
                      'cycle': 100,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 376,
                      'rate_ml_h': 957.4468,
                      'red_alert': False,
                      'ts': 1776094056},
                  {   'alert': 0,
                      'cycle': 99,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 661,
                      'rate_ml_h': 544.6293,
                      'red_alert': False,
                      'ts': 1776093680},
                  {   'alert': 0,
                      'cycle': 98,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 52327,
                      'rate_ml_h': 6.879813,
                      'red_alert': False,
                      'ts': 1776093019},
                  {   'alert': 0,
                      'cycle': 97,
                      'dev_sigma': 0,
                      'hour': 2,
                      'interval_s': 2653,
                      'rate_ml_h': 135.6954,
                      'red_alert': False,
                      'ts': 1776040692},
                  {   'alert': 0,
                      'cycle': 96,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 1196,
                      'rate_ml_h': 301.0034,
                      'red_alert': False,
                      'ts': 1776038039},
                  {   'alert': 0,
                      'cycle': 95,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 2311,
                      'rate_ml_h': 155.7767,
                      'red_alert': False,
                      'ts': 1776036843},
                  {   'alert': 0,
                      'cycle': 94,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 1651,
                      'rate_ml_h': 218.0497,
                      'red_alert': False,
                      'ts': 1776034532},
                  {   'alert': 0,
                      'cycle': 93,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 1691,
                      'rate_ml_h': 212.8918,
                      'red_alert': False,
                      'ts': 1776032881},
                  {   'alert': 0,
                      'cycle': 92,
                      'dev_sigma': 0,
                      'hour': 23,
                      'interval_s': 2143,
                      'rate_ml_h': 167.9888,
                      'red_alert': False,
                      'ts': 1776031190},
                  {   'alert': 0,
                      'cycle': 91,
                      'dev_sigma': 0,
                      'hour': 23,
                      'interval_s': 2588,
                      'rate_ml_h': 139.1036,
                      'red_alert': False,
                      'ts': 1776029047},
                  {   'alert': 0,
                      'cycle': 90,
                      'dev_sigma': 0,
                      'hour': 22,
                      'interval_s': 2585,
                      'rate_ml_h': 139.265,
                      'red_alert': False,
                      'ts': 1776026459},
                  {   'alert': 0,
                      'cycle': 89,
                      'dev_sigma': 0,
                      'hour': 21,
                      'interval_s': 4041,
                      'rate_ml_h': 89.08685,
                      'red_alert': False,
                      'ts': 1776023874},
                  {   'alert': 0,
                      'cycle': 88,
                      'dev_sigma': 0,
                      'hour': 20,
                      'interval_s': 3714,
                      'rate_ml_h': 96.93053,
                      'red_alert': False,
                      'ts': 1776019833},
                  {   'alert': 0,
                      'cycle': 87,
                      'dev_sigma': 0,
                      'hour': 19,
                      'interval_s': 1612,
                      'rate_ml_h': 223.3251,
                      'red_alert': False,
                      'ts': 1776016119},
                  {   'alert': 0,
                      'cycle': 86,
                      'dev_sigma': 0,
                      'hour': 19,
                      'interval_s': 3359,
                      'rate_ml_h': 107.1748,
                      'red_alert': False,
                      'ts': 1776014507}],
    'ema_rate_now': 154.3453,
    'fetched_at': '2026-04-15T16:04:59',
    'initial_ema': 149.83570481256575,
    'record_count': 60,
    'source': 'http://192.168.10.2'}


def print_raw():
    """Print the raw device snapshot for inspection."""
    SEP = "─" * 76
    print()
    print(SEP)
    print("  RAW DEVICE SNAPSHOT")
    print(SEP)
    print(f"  Fetched at     : {_RAW['fetched_at']}")
    print(f"  Source         : {_RAW['source']}")
    print(f"  EMA on device  : {_RAW['ema_rate_now']:.2f} ml/h")
    print(f"  EMA₀ back-calc : {_RAW['initial_ema']:.4f} ml/h  "
          f"(EMA before oldest buffered record)")
    print(f"  Records        : {_RAW['record_count']}")
    print()
    print(f"  {' #':>4}  {' timestamp':^20}  {'rate_ml_h':>10}"
          f"  {'interval_s':>10}  {'alert':>5}  {'cycle':>5}")
    print(f"  {'-'*62}")
    for i, rec in enumerate(_RAW['cycles']):
        print(
            f"  {i:>4}  {str(rec.get('ts','?')):^20}"
            f"  {rec.get('rate_ml_h', 0):>10.2f}"
            f"  {rec.get('interval_s', 0):>10.1f}"
            f"  {rec.get('alert', 0):>5}"
            f"  {rec.get('cycle', 0):>5}"
        )
    print(SEP)
    print()


# ═══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    # 1. Show raw data
    print_raw()

    # 2. Patch sim1 zone globals so zone() colouring matches device settings
    sim1.ZONE_GREEN  = ZONE_GREEN
    sim1.ZONE_YELLOW = ZONE_YELLOW

    # 3. Run simulation
    rows = sim1.simulate(FLOW_RATES, INITIAL_EMA, ALPHA, CLAMP, P1, P2)
    sim1.print_table(rows, INITIAL_EMA, ALPHA, CLAMP, P1, P2)
